certificates:
  certManager:
    # Enable cert manager integration. Cert manager should be already installed at the k8s cluster
    enabled: true
    version: ""
  # If cert-manager integration is disabled, upload certs data (ca.crt, tls.crt and tls.key) as k8s secretName in the namespace
  secretName: gmsa-server-cert

credential:
  enabled: true
  enableNonJoined: false # Populates hostAccountConfig field
  hostAccountConfig:
    pluginGUID: "" # CCG Plugin GUID
    portableCcgVersion: "1" # This needs to equal the current version of CCG which right now is '1'
    pluginInput: "" # Format of this field is dependent upon specific CCG Plugin
  domainJoinConfig:
    dnsName: ""  #DNS Domain Name
    dnsTreeName: "" #DNS Domain Name Root
    guid: ""  # Active Directory Domain GUID
    machineAccountName: "" #Username of the GMSA account
    netBiosName: ""  #NETBIOS name for the Active Directory Domain
    sid: "" #SID the Active Directory Domain

image:
  repository: rancher/mirrored-sigwindowstools-k8s-gmsa-webhook
  tag: v0.3.0
  imagePullPolicy: IfNotPresent

global:
  cattle:
    systemDefaultRegistry: ""
  kubectl:
    repository: rancher/kubectl
    tag: v1.22.6
    pullPolicy: IfNotPresent

## SecurityContext holds pod-level security attributes and common container settings.
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
##
podSecurityContext:
  runAsNonRoot: false
  # Currently, required to run as root due to port binding within the container.
  runAsUser: 0
securityContext: {}

tolerations: []
podDisruptionBudget:
  enabled: false
  minAvailable:
  maxUnavailable:
