global:
  cattle:
    systemDefaultRegistry: ""

  kubectl:
    repository: rancher/kubectl
    tag: v1.24.17
    pullPolicy: IfNotPresent

  imagePullSecrets: []
  # - name: "image-pull-secret"

nameOverride: ""

namespaceOverride: ""

image:
  repository: rancher/gmsa-account-provider
  tag: v0.2.0-rc1
  imagePullPolicy: IfNotPresent

certificates:
  certManager:
    enabled: true
    version: ""
    caCert:
      duration: "87600h0m0s" # TODO: modify to reasonable default
      renewBefore: "360h0m0s"
      privateKey: 
        rotationPolicy: Always # TODO: verify this works
        algorithm: RSA
        size: 4096
        encoding: PKCS8
    clientCert:
      duration: "87600h0m0s"
      renewBefore: "360h0m0s"
      privateKey: 
        rotationPolicy: Always # TODO: verify this works
        algorithm: RSA
        size: 4096
        encoding: PKCS8
      usages:
      - server auth
      - client auth
      dnsNames:
      - https://localhost
      - localhost
    serverCert:
      duration: "87600h0m0s" # TODO: modify to reasonable default
      renewBefore: "360h0m0s"
      privateKey: 
        rotationPolicy: Always # TODO: verify this works
        algorithm: RSA
        size: 4096
        encoding: PKCS8
      usages:
      - server auth
      - client auth
      dnsNames:
      - https://localhost
      - localhost
  caSecretName: ca-cert
  clientSecretName: ccg-dll-cert
  serverSecretName: account-provider-cert

nodeSelector: {}

affinity: {}

tolerations: []
# - key: "key"
#   operator: "Equal"
#   value: "value"
#   effect: "NoSchedule"

securityContext:
  windowsOptions:
    hostProcess: true
    runAsUserName: "NT AUTHORITY\\SYSTEM"